#!/bin/bash
# does an update
echo -e "\e[32m:: updating system...\e[39m"
echo -e "\e[34m:: updating pacman...\e[39m"
sudo pacman -Syu
retVal=$?
if [ $retVal -ne 0 ]; then
    echo -e "\e[31m:: Arg!.... will exit...\e[39m"
fi
echo -e "\e[34m:: updating yay...\e[39m"
yay -Syua
retVal=$?
if [ $retVal -ne 0 ]; then
    echo -e "\e[31m:: Arg!.... will exit...\e[39m"
fi
echo " "
echo -e "\e[32m:: update complete...\e[39m"
echo " "
sleep 1s
# function to check for and remove orphan packages
# this function looped by the while loop later
function orphanage {
echo -e "\e[32m:: checking if orphan packages exist on the system...\e[39m"
ORPHANS=`pacman -Qqdt`
if [ -z "$ORPHANS" ]
then
    echo -e "\e[32m:: Everything is OK, will exit...\e[39m"
    sleep 1s
    exit
else
    echo -e "\e[31m:: orphans found on the system.\n$ORPHANS\n\n:: Removing...\e[39m"
    sudo pacman -R --nosave $ORPHANS
fi
}
# end of orphan function
#
#
# infinite loop to find and remove orphan packages
# script exits when none found
while [ 1 ]
do
orphanage
done
# end of loop
#
#
# choose echo error message or zenity error message
echo -e "\e[31m:: ** update script did not exit normally!\e[39m"
#zenity --warning --text="Update script did not exit normally"
sleep 8s
exit
